### ISSUE TITLE
Broken hMETIS link at SCIP website

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [KarypisLab/METIS#35]
Hey,

[SCIP](https://www.scipopt.org/index.php#download) download page recommend installing [hMETIS](http://glaros.dtc.umn.edu/gkhome/fetch/sw/hmetis/) but the link is not working. Is it possible to update the link?

Thanks in advance!

**Comment by ischmidt20** [comment]
All of the METIS references point to that domain, I highly doubt it is a dead link, just that there is some issue with the domain at the moment

**Comment by MajidSKhoshghalb** [comment]
Thanks , but I've tried last week too.

**Comment by ischmidt20** [comment]
Hmm I've just started with Metis in the last couple days, so disheartening to see that the issue has lasted for that long. Don't think there are any alternate sources though because Google, etc. all point to that domain. This repo doesn't seem particularly active but hopefully someone will notice and get everything back up

**Comment by MajidSKhoshghalb** [comment]
I already contacted SCIP team, but Franziska didn't get back to me.

**Comment by karypis** [comment]
The server was down over the summer. Everything is up now.

**Comment by magneticflux-** [comment]
The server seems to be down again, and has been for several days at least. I was building GCG (part of the SCIP suite) and it optionally uses `hMetis` to detect arrowhead structures.

For anyone else looking for a copy, I found that GCG's GitLab CI uses this URL to download `hMetis-2.0pre1`: https://or.rwth-aachen.de/hmetis/hmetis-2.0pre1.tar.gz
